### ISSUE TITLE
Build 94 appears to be broken

### ISSUE THREAD

**Issue by rkfox** [wchen342/ungoogled-chromium-fedora#15]
I followed the steps in the readme as best I could. It appears to not compile properly. A number of the patches do not apply as they cannot find the file to patch. After commenting out the patches that do not work, the build fails later at `+ build/linux/unbundle/remove_bundled_libraries.py` with a lot of path arguments. Prior to that is also an error `ERROR: 15462 files could not be pruned.`.

Trying to compile version 94.0.4606.71.

This occurs with and without `%global freeworld 1`.

I also had to compile using `pmbuild --define "_topdir `pwd`" -v -bb SPECS/ungoogled-chromium.spec`.

Patch error (patch #52, #53, #56, #57, #60, #62, #65, #67, #68, #86, #96, and #400 all look like this):
```
Patch #52 (chromium-81.0.4044.92-unbundle-zlib.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 -b --suffix .unbundle-zlib --fuzz=0
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -up chromium-81.0.4044.92/third_party/perfetto/gn/BUILD.gn.unbundle-zlib chromium-81.0.4044.92/third_party/perfetto/gn/BUILD.gn
|--- chromium-81.0.4044.92/third_party/perfetto/gn/BUILD.gn.unbundle-zlib	2020-04-13 12:25:09.001172601 -0400
|+++ chromium-81.0.4044.92/third_party/perfetto/gn/BUILD.gn	2020-04-13 12:25:23.688921586 -0400
--------------------------
File to patch: 

```

Pruning errors (with above patches commented out):
```
+ python3 -B /home/user/projects/ungoogled-chromium/ungoogled-chromium-fedora/BUILD/../BUILD/ungoogled-chromium-94.0.4606.71-1/utils/prune_binaries.py . /home/user/projects/ungoogled-chromium/ungoogled-chromium-fedora/BUILD/../BUILD/ungoogled-chromium-94.0.4606.71-1/pruning.list
ERROR: 15462 files could not be pruned.
+ true
+ mkdir -p third_party/node/linux/node-linux-x64/bin
+ ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/node
+ build/linux/unbundle/remove_bundled_libraries.py base/third_party/cityhash base/third_party/cityhash_v103 base/third_party/double_conversion base/third_party/dynamic_annotations base/third_party/icu base/third_party/libevent base/third_party/nspr base/third_party/superfasthash base/third_party/symbolize base/third_party/valgrind base/third_party/xdg_mime base/third_party/xdg_user_dirs buildtools/third_party/eu-strip buildtools/third_party/libc++ buildtools/third_party/libc++abi chrome/third_party/mozilla_security_manager courgette/third_party net/third_party/mozilla_security_manager net/third_party/nss net/third_party/quiche net/third_party/uri_template third_party/abseil-cpp third_party/angle third_party/angle/src/common/third_party/base third_party/angle/src/common/third_party/smhasher third_party/angle/src/common/third_party/xxhash third_party/angle/src/third_party/libXNVCtrl third_party/angle/src/third_party/trace_event third_party/angle/src/third_party/volk third_party/apple_apsl third_party/axe-core third_party/blanketjs third_party/blink third_party/boringssl third_party/boringssl/src/third_party/fiat third_party/breakpad third_party/breakpad/breakpad/src/third_party/curl third_party/brotli third_party/catapult third_party/catapult/common/py_vulcanize/third_party/rcssmin third_party/catapult/common/py_vulcanize/third_party/rjsmin third_party/catapult/third_party/beautifulsoup4 third_party/catapult/third_party/google-endpoints third_party/catapult/third_party/html5lib-python third_party/catapult/third_party/polymer third_party/catapult/third_party/six third_party/catapult/tracing/third_party/d3 third_party/catapult/tracing/third_party/gl-matrix third_party/catapult/tracing/third_party/jpeg-js third_party/catapult/tracing/third_party/jszip third_party/catapult/tracing/third_party/mannwhitneyu third_party/catapult/tracing/third_party/oboe third_party/catapult/tracing/third_party/pako third_party/ced third_party/cld_3 third_party/closure_compiler third_party/crashpad third_party/crashpad/crashpad/third_party/lss third_party/crashpad/crashpad/third_party/zlib/ third_party/crc32c third_party/cros_system_api third_party/dav1d third_party/dawn third_party/dawn/third_party/khronos third_party/dawn/third_party/tint third_party/depot_tools third_party/devscripts third_party/devtools-frontend third_party/devtools-frontend/src/third_party/typescript third_party/devtools-frontend/src/front_end/third_party/acorn third_party/devtools-frontend/src/front_end/third_party/axe-core third_party/devtools-frontend/src/front_end/third_party/chromium third_party/devtools-frontend/src/front_end/third_party/codemirror third_party/devtools-frontend/src/front_end/third_party/diff third_party/devtools-frontend/src/front_end/third_party/i18n third_party/devtools-frontend/src/front_end/third_party/intl-messageformat third_party/devtools-frontend/src/front_end/third_party/lighthouse third_party/devtools-frontend/src/front_end/third_party/lit-html third_party/devtools-frontend/src/front_end/third_party/lodash-isequal third_party/devtools-frontend/src/front_end/third_party/marked third_party/devtools-frontend/src/front_end/third_party/puppeteer third_party/devtools-frontend/src/front_end/third_party/wasmparser third_party/devtools-frontend/src/test/unittests/front_end/third_party/i18n third_party/dom_distiller_js third_party/eigen3 third_party/emoji-segmenter third_party/expat third_party/farmhash third_party/fdlibm third_party/ffmpeg third_party/fft2d third_party/flac third_party/flatbuffers third_party/fontconfig third_party/freetype third_party/fusejs third_party/gemmlowp third_party/google_input_tools third_party/google_input_tools/third_party/closure_library third_party/google_input_tools/third_party/closure_library/third_party/closure third_party/google_trust_services third_party/googletest third_party/grpc third_party/harfbuzz-ng third_party/highway third_party/hunspell third_party/iccjpeg third_party/icu third_party/inspector_protocol third_party/jinja2 third_party/jsoncpp third_party/jstemplate third_party/khronos third_party/leveldatabase third_party/libXNVCtrl third_party/libaddressinput third_party/libaom third_party/libaom/source/libaom/third_party/fastfeat third_party/libaom/source/libaom/third_party/vector third_party/libaom/source/libaom/third_party/x86inc third_party/libavif third_party/libdrm third_party/libgav1 third_party/libgifcodec third_party/libjingle third_party/libjpeg_turbo third_party/libjxl third_party/libphonenumber third_party/libpng third_party/libsecret third_party/libsrtp third_party/libsync third_party/libudev third_party/liburlpattern third_party/libusb third_party/libva_protected_content third_party/libvpx third_party/libvpx/source/libvpx/third_party/x86inc third_party/libwebm third_party/libwebp third_party/libx11 third_party/libxcb-keysyms third_party/libxml third_party/libxml/chromium third_party/libxslt third_party/libyuv third_party/libzip third_party/lottie third_party/lss third_party/lzma_sdk third_party/mako third_party/markupsafe third_party/mesa third_party/metrics_proto third_party/minigbm third_party/modp_b64 third_party/nasm third_party/nearby third_party/neon_2_sse third_party/node third_party/node/node_modules/polymer-bundler/lib/third_party/UglifyJS2 third_party/one_euro_filter third_party/opencv third_party/openscreen third_party/openscreen/src/third_party/mozilla third_party/openscreen/src/third_party/tinycbor third_party/opus third_party/ots third_party/pdfium third_party/pdfium/third_party/agg23 third_party/pdfium/third_party/base third_party/pdfium/third_party/bigint third_party/pdfium/third_party/freetype third_party/pdfium/third_party/lcms third_party/pdfium/third_party/libopenjpeg20 third_party/pdfium/third_party/libpng16 third_party/pdfium/third_party/libtiff third_party/pdfium/third_party/skia_shared third_party/perfetto third_party/perfetto/protos/third_party/chromium third_party/pffft third_party/ply third_party/polymer third_party/private-join-and-compute third_party/private_membership third_party/protobuf third_party/protobuf/third_party/six third_party/pyjson5 third_party/qcms third_party/qunit third_party/re2 third_party/rnnoise third_party/ruy third_party/s2cellid third_party/securemessage third_party/shell-encryption third_party/simplejson third_party/sinonjs third_party/skia third_party/skia/include/third_party/skcms third_party/skia/include/third_party/vulkan third_party/skia/third_party/skcms third_party/skia/third_party/vulkan third_party/smhasher third_party/snappy third_party/speech-dispatcher third_party/sqlite third_party/swiftshader third_party/swiftshader/third_party/astc-encoder third_party/swiftshader/third_party/llvm-subzero third_party/swiftshader/third_party/llvm-10.0 third_party/swiftshader/third_party/marl third_party/swiftshader/third_party/subzero third_party/swiftshader/third_party/SPIRV-Headers third_party/tcmalloc third_party/tensorflow-text third_party/test_fonts third_party/tflite third_party/tflite/src/third_party/eigen3 third_party/tflite/src/third_party/fft2d third_party/tflite-support third_party/ukey2 third_party/usb_ids third_party/usrsctp third_party/utf third_party/vulkan third_party/wayland third_party/web-animations-js third_party/webdriver third_party/webgpu-cts third_party/webrtc third_party/webrtc/common_audio/third_party/ooura third_party/webrtc/common_audio/third_party/spl_sqrt_floor third_party/webrtc/modules/third_party/fft third_party/webrtc/modules/third_party/g711 third_party/webrtc/modules/third_party/g722 third_party/webrtc/rtc_base/third_party/base64 third_party/webrtc/rtc_base/third_party/sigslot third_party/widevine third_party/woff2 third_party/wuffs third_party/x11proto third_party/xcbproto third_party/xdg-utils third_party/zxcvbn-cpp third_party/zlib third_party/zlib/google tools/gn/src/base/third_party/icu url/third_party/mozilla v8/src/third_party/siphash v8/src/third_party/utf8-decoder v8/src/third_party/valgrind v8/third_party/v8 v8/third_party/inspector_protocol --do-remove
third_party/angle does not exist
third_party/angle/src/common/third_party/base does not exist
third_party/angle/src/common/third_party/smhasher does not exist
third_party/angle/src/common/third_party/xxhash does not exist
third_party/angle/src/third_party/libXNVCtrl does not exist
third_party/angle/src/third_party/trace_event does not exist
third_party/angle/src/third_party/volk does not exist
third_party/boringssl/src/third_party/fiat does not exist
third_party/breakpad/breakpad/src/third_party/curl does not exist
third_party/catapult does not exist
third_party/catapult/common/py_vulcanize/third_party/rcssmin does not exist
third_party/catapult/common/py_vulcanize/third_party/rjsmin does not exist
third_party/catapult/third_party/beautifulsoup4 does not exist
third_party/catapult/third_party/google-endpoints does not exist
third_party/catapult/third_party/html5lib-python does not exist
third_party/catapult/third_party/polymer does not exist
third_party/catapult/third_party/six does not exist
third_party/catapult/tracing/third_party/d3 does not exist
third_party/catapult/tracing/third_party/gl-matrix does not exist
third_party/catapult/tracing/third_party/jpeg-js does not exist
third_party/catapult/tracing/third_party/jszip does not exist
third_party/catapult/tracing/third_party/mannwhitneyu does not exist
third_party/catapult/tracing/third_party/oboe does not exist
third_party/catapult/tracing/third_party/pako does not exist
third_party/cros_system_api does not exist
third_party/dawn does not exist
third_party/dawn/third_party/khronos does not exist
third_party/dawn/third_party/tint does not exist
third_party/depot_tools does not exist
third_party/devtools-frontend does not exist
third_party/devtools-frontend/src/third_party/typescript does not exist
third_party/devtools-frontend/src/front_end/third_party/acorn does not exist
third_party/devtools-frontend/src/front_end/third_party/axe-core does not exist
third_party/devtools-frontend/src/front_end/third_party/chromium does not exist
third_party/devtools-frontend/src/front_end/third_party/codemirror does not exist
third_party/devtools-frontend/src/front_end/third_party/diff does not exist
third_party/devtools-frontend/src/front_end/third_party/i18n does not exist
third_party/devtools-frontend/src/front_end/third_party/intl-messageformat does not exist
third_party/devtools-frontend/src/front_end/third_party/lighthouse does not exist
third_party/devtools-frontend/src/front_end/third_party/lit-html does not exist
third_party/devtools-frontend/src/front_end/third_party/lodash-isequal does not exist
third_party/devtools-frontend/src/front_end/third_party/marked does not exist
third_party/devtools-frontend/src/front_end/third_party/puppeteer does not exist
third_party/devtools-frontend/src/front_end/third_party/wasmparser does not exist
third_party/devtools-frontend/src/test/unittests/front_end/third_party/i18n does not exist
third_party/ffmpeg does not exist
third_party/flac does not exist
third_party/libaom/source/libaom/third_party/fastfeat does not exist
third_party/libaom/source/libaom/third_party/vector does not exist
third_party/libaom/source/libaom/third_party/x86inc does not exist
third_party/libgifcodec does not exist
third_party/libjpeg_turbo does not exist
third_party/libsrtp does not exist
third_party/libvpx/source/libvpx/third_party/x86inc does not exist
third_party/libyuv does not exist
third_party/lss does not exist
third_party/nasm does not exist
third_party/node/node_modules/polymer-bundler/lib/third_party/UglifyJS2 does not exist
third_party/openscreen/src/third_party/mozilla does not exist
third_party/openscreen/src/third_party/tinycbor does not exist
third_party/pdfium does not exist
third_party/pdfium/third_party/agg23 does not exist
third_party/pdfium/third_party/base does not exist
third_party/pdfium/third_party/bigint does not exist
third_party/pdfium/third_party/freetype does not exist
third_party/pdfium/third_party/lcms does not exist
third_party/pdfium/third_party/libopenjpeg20 does not exist
third_party/pdfium/third_party/libpng16 does not exist
third_party/pdfium/third_party/libtiff does not exist
third_party/pdfium/third_party/skia_shared does not exist
third_party/perfetto does not exist
third_party/perfetto/protos/third_party/chromium does not exist
third_party/skia does not exist
third_party/skia/include/third_party/skcms does not exist
third_party/skia/include/third_party/vulkan does not exist
third_party/skia/third_party/skcms does not exist
third_party/skia/third_party/vulkan does not exist
third_party/swiftshader does not exist
third_party/swiftshader/third_party/astc-encoder does not exist
third_party/swiftshader/third_party/llvm-subzero does not exist
third_party/swiftshader/third_party/llvm-10.0 does not exist
third_party/swiftshader/third_party/marl does not exist
third_party/swiftshader/third_party/subzero does not exist
third_party/swiftshader/third_party/SPIRV-Headers does not exist
third_party/tflite/src/third_party/eigen3 does not exist
third_party/tflite/src/third_party/fft2d does not exist
third_party/vulkan does not exist
third_party/webrtc/common_audio/third_party/ooura does not exist
third_party/webrtc/common_audio/third_party/spl_sqrt_floor does not exist
third_party/webrtc/modules/third_party/fft does not exist
third_party/webrtc/modules/third_party/g711 does not exist
third_party/webrtc/modules/third_party/g722 does not exist
third_party/webrtc/rtc_base/third_party/base64 does not exist
third_party/webrtc/rtc_base/third_party/sigslot does not exist
third_party/xdg-utils does not exist
tools/gn/src/base/third_party/icu does not exist
v8/src/third_party/siphash does not exist
v8/src/third_party/utf8-decoder does not exist
v8/src/third_party/valgrind does not exist
v8/third_party/v8 does not exist
v8/third_party/inspector_protocol does not exist
error: Bad exit status from /var/tmp/rpm-tmp.Et1Vvj (%prep)


RPM build errors:
    bogus date in %changelog: Wed Sep 28 2021 wchen342 <> - 94.0.4606.61-1
    bogus date in %changelog: Mon Sep  4 2021 wchen342 <> - 93.0.4577.63-1
    Bad exit status from /var/tmp/rpm-tmp.Et1Vvj (%prep)
```

**Comment by wchen342** [comment]
I suspect the tarball from github is simply a mirror of chromium source tree itself, not the whole archive with `gclient sync` run on top of it. So what usually happens in a standard chromium build (checkout from source) is that:
 - you checkout the chromium source tree at `https://chromium.googlesource.com/chromium/src.git`
 - you checkout `depots_tools` and set up environment variables, config, etc.
 - run `gclient sync` on the source tree in step 1, which will download a bunch of extra files and sources
 - you build on the synced source

I suspect the Github source is simply a mirror of step 1, not synced source like from `https://commondatastorage.googleapis.com/chromium-browser-official/chromium-%{version}.tar.xz`. You can verify it by open the source tarball you get from Github and see whether there is a `third_party/angle` folder.

**Comment by rkfox** [comment]
The archive from googleapis.com fixed the errors I was having. All of the patches are applied properly. It does have `third_party/angle` but it still does not build.
```
[194/194] LINK gn
ERROR at //third_party/webrtc/BUILD.gn:125:5: Replacing nonempty list.
    defines = [ "WEBRTC_ENABLE_OBJC_SYMBOL_EXPORT" ]
    ^------
This overwrites a previously-defined nonempty list with another nonempty list.
See //third_party/webrtc/BUILD.gn:122:15: for previous definition
    defines = [ "WEBRTC_ENABLE_SYMBOL_EXPORT" ]
              ^-------------------------------
Did you mean to append/modify instead? If you really want to overwrite, do:
  foo = []
before reassigning.
See //third_party/webrtc/webrtc.gni:354:22: which caused the file to be included.
rtc_prod_configs = [ webrtc_root + ":rtc_prod_config" ]
                     ^----------
Traceback (most recent call last):
  File "/home/user/projects/ungoogled-chromium/ungoogled-chromium-fedora/BUILD/chromium-94.0.4606.71/tools/gn/bootstrap/bootstrap.py", line 144, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/user/projects/ungoogled-chromium/ungoogled-chromium-fedora/BUILD/chromium-94.0.4606.71/tools/gn/bootstrap/bootstrap.py", line 137, in main
    subprocess.check_call([
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/user/projects/ungoogled-chromium/ungoogled-chromium-fedora/BUILD/chromium-94.0.4606.71/out/Release/gn', 'gen', '/home/user/projects/ungoogled-chromium/ungoogled-chromium-fedora/BUILD/chromium-94.0.4606.71/out/Release', ' --script-executable=/usr/bin/python3', '--args= is_debug=false is_official_build=false is_unsafe_developer_build=false dcheck_always_on=false system_libdir="lib64" google_api_key="" google_default_client_id="" google_default_client_secret="" is_clang=false use_sysroot=false disable_fieldtrial_testing_config=true use_lld=false rtc_enable_symbol_export=true use_gold=false ffmpeg_branding="ChromeOS" proprietary_codecs=true treat_warnings_as_errors=false use_custom_libcxx=false use_gnome_keyring=false use_glib=false use_gio=true use_pulseaudio=true icu_use_data_file=true enable_nacl=false is_component_ffmpeg=false is_component_build=false enable_hangout_services_extension=false blink_symbol_level=0 symbol_level=0 exclude_unwind_tables=true enable_widevine=true use_vaapi=true rtc_use_pipewire=true rtc_link_pipewire=true chrome_pgo_phase=0 enable_js_type_check=false enable_mse_mpeg2ts_stream_parser=true enable_nacl_nonsfi=false enable_one_click_signin=false enable_reading_list=false enable_remoting=false enable_reporting=false enable_service_discovery=false safe_browsing_mode=0 is_debug=false', '--root=/home/user/projects/ungoogled-chromium/ungoogled-chromium-fedora/BUILD/chromium-94.0.4606.71']' returned non-zero exit status 1.
error: Bad exit status from /var/tmp/rpm-tmp.NWGZAp (%prep)


RPM build errors:
    bogus date in %changelog: Wed Sep 28 2021 wchen342 <feiyu2817@gmail.com> - 94.0.4606.61-1
    bogus date in %changelog: Mon Sep  4 2021 wchen342 <feiyu2817@gmail.com> - 93.0.4577.63-1
    Bad exit status from /var/tmp/rpm-tmp.NWGZAp (%prep)
```

**Comment by wchen342** [comment]
The path substitution warnings are normal, they always print those.

**Comment by wchen342** [comment]
When is the error printed? The `exit 0` means the build finished without error. Is there an rpm file in `RPMS`?
The warning means `AVX` is unavailable for the compiler. Does you CPU support AVX?
